#define RC_SHADER_TEXTURE_KIND_DIFFUSE   1 << 7
#define RC_SHADER_TEXTURE_KIND_NORMAL    1 << 8
#define RC_SHADER_TEXTURE_KIND_SPECULAR  1 << 9
#define RC_SHADER_TEXTURE_KIND_ROUGNESS  1 << 10
#define RC_SHADER_TEXTURE_KIND_METALLIC  1 << 11
#define RC_SHADER_TEXTURE_KIND_OCCLUSION 1 << 12
#define RC_SHADER_TEXTURE_KIND_EMISSION  1 << 13

#define RC_VERTEX_SHADER_ATTRIB_LOCATION_POSITION   0
#define RC_VERTEX_SHADER_ATTRIB_LOCATION_NORMAL     1
#define RC_VERTEX_SHADER_ATTRIB_LOCATION_TANGENT    2
#define RC_VERTEX_SHADER_ATTRIB_LOCATION_TEXCOORD_0 3

#define RC_FRAGMENT_SHADER_TEXTURE_BINDING_DIFFUSE  0
#define RC_FRAGMENT_SHADER_TEXTURE_BINDING_NORMAL   1
#define RC_FRAGMENT_SHADER_TEXTURE_BINDING_SPECULAR 2
#define RC_FRAGMENT_SHADER_TEXTURE_BINDING_ROUGH_METAL_OCCLUSION 3
#define RC_FRAGMENT_SHADER_TEXTURE_BINDING_EMISSION 4
