#define RC_SHADER_TEXTURE_KIND_BASE_COLOR          1 << 1
#define RC_SHADER_TEXTURE_KIND_NORMAL              1 << 2
#define RC_SHADER_TEXTURE_KIND_ROUGNESS_METALLIC   1 << 3
#define RC_SHADER_TEXTURE_KIND_OCCLUSION           1 << 4
#define RC_SHADER_TEXTURE_KIND_EMISSION            1 << 5
#define RC_SHADER_TEXTURE_KIND_SPECULAR_GLOSSINESS 1 << 6

#define RC_SHADER_TEXTURE_SEPARATE_OCCLUSION       1 << 13
#define RC_SHADER_TEXTURE_BLEND                    1 << 14
#define RC_SHADER_TEXTURE_ALPHA_MASK               1 << 15

#define RC_VERTEX_SHADER_ATTRIB_LOCATION_POSITION   0
#define RC_VERTEX_SHADER_ATTRIB_LOCATION_NORMAL     1
#define RC_VERTEX_SHADER_ATTRIB_LOCATION_TANGENT    2
#define RC_VERTEX_SHADER_ATTRIB_LOCATION_TEXCOORD_0 3

#define RC_FRAGMENT_SHADER_TEXTURE_BINDING_DIFFUSE  0
#define RC_FRAGMENT_SHADER_TEXTURE_BINDING_NORMAL   1
#define RC_FRAGMENT_SHADER_TEXTURE_BINDING_SPECULAR 2
#define RC_FRAGMENT_SHADER_TEXTURE_BINDING_ROUGHNESS_METALLIC 3
#define RC_FRAGMENT_SHADER_TEXTURE_BINDING_OCCLUSION 4
#define RC_FRAGMENT_SHADER_TEXTURE_BINDING_EMISSION 5
